apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gforce.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gforce.labels" . | nindent 4 }}
type: Opaque
data:
  jwt-secret: {{ .Values.server.jwtSecret | b64enc | quote }}
  db-dsn: {{ include "gforce.dbDSN" . | b64enc | quote }}
