apiVersion: v1
kind: Service
metadata:
  name: {{ include "gforce.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gforce.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
    - name: ssh
      port: {{ .Values.server.sshPort }}
      targetPort: ssh
      protocol: TCP
  selector:
    {{- include "gforce.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: server
